batch_size: 8
block_size: 128
max_iters: 1000000
eval_interval: 100
save_interval: 500
learning_rate: 0.001
eval_iters: 200
n_embd: 128
n_head: 4
n_layer: 4
dropout: 0.01
vocab_size: 389
device: "cuda"
generated_event_length: 300