experiment: 'embedding256-layer6'
max_seq: 256
embedding_dim: 128
num_layers: 6
event_dim: 388
fp16:
pickle_dir: 'dataset/preprocess'
epochs: 500
batch_size: 8
load_path:
dropout: 0.1
debug: 'true'
l_r: 0.01
label_smooth: 0.1
